const Ancestors = [{
  image: 'ancestor1.jpg',
  name: "John Doe",
  dateOfBirth: "March 4, 1876",
  dateOfDeath: "May 9, 1946",
  placeOfBirth: "Eugene, Oregon",
  placeOfDeath: "Kanab, Utah",
},
{
  image: 'ancestor1.jpg',
  name: "Stacey Chambers",
  dateOfBirth: "December 21, 1977",
  dateOfDeath: "January 9, 2013",
  placeOfBirth: "San Diego, California",
  placeOfDeath: "Austin, Texas",
},
{
  image: 'ancestor1.jpg',
  name: "Johnathan Oglesbead",
  dateOfBirth: "February 12, 1944",
  dateOfDeath: "June 6, 2000",
  placeOfBirth: "Germany",
  placeOfDeath: "France",
},
{
  image: 'ancestor1.jpg',
  name: "Kathrine McBean",
  dateOfBirth: "April 26, 1899",
  dateOfDeath: "October 7, 1965",
  placeOfBirth: "Plano, Idaho",
  placeOfDeath: "Seattle, Washington",
},
{
  image: 'ancestor1.jpg',
  name: "John Doe",
  dateOfBirth: "March 4, 1876",
  dateOfDeath: "May 9, 1946",
  placeOfBirth: "Eugene, Oregon",
  placeOfDeath: "Kanab, Utah",
},
{
  image: 'ancestor1.jpg',
  name: "Stacey Chambers",
  dateOfBirth: "December 21, 1977",
  dateOfDeath: "January 9, 2013",
  placeOfBirth: "San Diego, California",
  placeOfDeath: "Austin, Texas",
},
{
  image: 'ancestor1.jpg',
  name: "Johnathan Oglesbead",
  dateOfBirth: "February 12, 1944",
  dateOfDeath: "June 6, 2000",
  placeOfBirth: "Germany",
  placeOfDeath: "France",
},
{
  image: 'ancestor1.jpg',
  name: "Kathrine McBean",
  dateOfBirth: "April 26, 1899",
  dateOfDeath: "October 7, 1965",
  placeOfBirth: "Plano, Idaho",
  placeOfDeath: "Seattle, Washington",
},
{
  image: 'ancestor1.jpg',
  name: "John Doe",
  dateOfBirth: "March 4, 1876",
  dateOfDeath: "May 9, 1946",
  placeOfBirth: "Eugene, Oregon",
  placeOfDeath: "Kanab, Utah",
},
{
  image: 'ancestor1.jpg',
  name: "Stacey Chambers",
  dateOfBirth: "December 21, 1977",
  dateOfDeath: "January 9, 2013",
  placeOfBirth: "San Diego, California",
  placeOfDeath: "Austin, Texas",
},
{
  image: 'ancestor1.jpg',
  name: "Johnathan Oglesbead",
  dateOfBirth: "February 12, 1944",
  dateOfDeath: "June 6, 2000",
  placeOfBirth: "Germany",
  placeOfDeath: "France",
},
{
  image: 'ancestor1.jpg',
  name: "Kathrine McBean",
  dateOfBirth: "April 26, 1899",
  dateOfDeath: "October 7, 1965",
  placeOfBirth: "Plano, Idaho",
  placeOfDeath: "Seattle, Washington",
},
{
  image: 'ancestor1.jpg',
  name: "John Doe",
  dateOfBirth: "March 4, 1876",
  dateOfDeath: "May 9, 1946",
  placeOfBirth: "Eugene, Oregon",
  placeOfDeath: "Kanab, Utah",
},
{
  image: 'ancestor1.jpg',
  name: "Stacey Chambers",
  dateOfBirth: "December 21, 1977",
  dateOfDeath: "January 9, 2013",
  placeOfBirth: "San Diego, California",
  placeOfDeath: "Austin, Texas",
},
{
  image: 'ancestor1.jpg',
  name: "Johnathan Oglesbead",
  dateOfBirth: "February 12, 1944",
  dateOfDeath: "June 6, 2000",
  placeOfBirth: "Germany",
  placeOfDeath: "France",
}]

export default Ancestors;
